### ISSUE TITLE
Add option to exclude certain metrics?

### ISSUE THREAD

**Issue by jduan-highnote** [int128/datadog-actions-metrics#1021]
We noticed that we started sending a lot more metrics recently and realized that those were `distribution` metrics. Is there a way to exclude certain metrics? This is from a cost perspective. The addition of `distribution` metrics is great but it's also very costly.

**Comment by jduan-highnote** [comment]
@int128 thoughts?

**Comment by int128** [comment]
`disable-distribution-metrics` option is available since v1.84.0

**Comment by jduan-highnote** [comment]
Thank you!
