### ISSUE TITLE
Metrics are wrong for retried workflows

### ISSUE THREAD

**Issue by jduan-highnote** [int128/datadog-actions-metrics#232]
Hi,

I believe metrics are wrong for retried workflows. It looks like when metrics (eg: workflow_run.duration_second) are calculated, the original start_time of the first run is used even for retried workflows. Can you double check? thanks.

**Comment by int128** [comment]
Currently this action calculates a time using `created_at` and `updated_at` because originally only those are available.

I noticed the following parameters are available in the payload.

```json
    "created_at": "2022-02-25T23:49:51Z",
    "run_started_at": "2022-02-25T23:49:51Z",
    "updated_at": "2022-02-25T23:50:43Z",
```

I think it is possible to calculate a time using `run_started_at` and `updated_at`.

**Comment by jduan-highnote** [comment]
@int128 good find. I agree those two variables should be used instead. Can you make a change? Thanks!

**Comment by int128** [comment]
I will try the fix 👍
