### ISSUE TITLE
queued_duration_second data seems wrong

### ISSUE THREAD

**Issue by jduan-highnote** [int128/datadog-actions-metrics#285]
This metric seems wrong. We have jobs that are clearly waiting for github action runners but the chart shows either negative numbers or zero for queuing time. Can you please check? thanks.

![Cursor_and_bayone_repo_core_metrics___Datadog](https://user-images.githubusercontent.com/92047874/163074952-73065932-bf58-4501-b92a-f8b798cc4ba1.png)

**Comment by mlahargou** [comment]
I was confused about this myself. From the README:
```
github.actions.job.queued_duration_second
  - Time from a job is started until the first step is started
```

Won't that always be 0 (or close to 0)? Once the job is picked up by a runner, the first step starts almost immediately. That's not very useful information.

I think the more important metric is "Time from a workflow is started until the job is started."  This better reflects how long a job was sitting in the queue waiting for a free runner to pick that job up.

I've got a snippet of code that should do the trick:
```diff
+++ b/src/workflowRun/metrics.ts
@@ -143,7 +143,8 @@ export const computeJobMetrics = (
 
     if (checkRun.steps.nodes.length > 0) {
       const firstStepStartedAt = Math.min(...checkRun.steps.nodes.map((s) => unixTime(s.startedAt)))
-      const queued = firstStepStartedAt - startedAt
+      const workflowRunStartedAt = unixTime(e.workflow_run.run_started_at)
+      const queued = firstStepStartedAt - workflowRunStartedAt
       series.push({
         host: 'github.com',
         tags,
```

**Comment by int128** [comment]
@mlahargou This metric would be suitable for that case. Could you check it?

```markdown
- `github.actions.workflow_run.queued_duration_second`
  - Time from a workflow is created until the first job is started
  - Available for the first workflow run only
```

I think the queued time of your change may be wrong value, if a job is run after another job such as `needs`.

**Comment by jduan-highnote** [comment]
@int128 can you explain what this metric `queued_duration_second` measures exactly? I'm interested in the time it takes for a job to be scheduled onto a runner. Context: we use self hosted runners that are persistent and we don't want to provision too many of them. So we only provide some. I'd like to know how often we run out of capacity, ie jobs are waiting to pick up a runner. Thanks!

**Comment by int128** [comment]
`queued_duration_second` is the time from a workflow is started until the first job of workflow is started. It is available only if `collect-job-metrics` is enabled.
The metric is calculated here:
https://github.com/int128/datadog-actions-metrics/blob/ceae39acb5862a52adbb1731f7d4a0008b71d0e1/src/workflowRun/metrics.ts#L77-L89

In our organization, we use this metric for monitoring the experience of self-hosted runner.

**Comment by mlahargou** [comment]
I think this metric is fine if all of the jobs in the workflow use the same runner. In our org, we have multiple runners and each job uses different runner labels. 

For example

```
jobs:
   unit:
      name: unit
      runs-on: [self-hosted, unit-runner]
      ...
   integration:
      name: integration
      runs-on: [self-hosted, integration-runner]
      ...
```

In this case, we'd like to be able to monitor each job and how long they are queued for. If the unit job gets picked up immediately but the integration job takes 1 hour to start, this metric would show a queue time of ~0 (b/c the unit job was picked up and started immediately). That doesn't really represent the full picture as the integration job was queued for an hour.

Ideally, we'd love a metric that was essentially time from when a job _could_ run until time the job _actually_ runs.

**Comment by int128** [comment]
It may be possible to calculate the total queued time of jobs in a workflow by this formula:

- (workflow run duration) - sum of (job duration)

For each job, it may be possible to calculate the queued time of a job by difference of these timestamp:

- completed time of the previous job
- started time of this job

I will try the implementation.

**Comment by jduan-highnote** [comment]
@int128 did you get a chance to try what you described in your last comment?

**Comment by int128** [comment]
Unfortunately, I think it is not possible to calculate the queued time from GitHub API, because we cannot determine when a job is  queued actually.

Instead, I'd like to suggest these metrics available in actions-runner-controller.
https://github.com/actions/actions-runner-controller/blob/c5d6842d5fb215c06ad3f948e51271a6aae82694/pkg/actionsmetrics/metrics.go#L75-L125

**Comment by int128** [comment]
These metrics are available now.

> - `github.actions.job.queued_duration_second`
>   - Time from a job is created to started (gauge)
> - `github.actions.job.queued_duration_second.distribution`
>   - Time from a job is created to started (distribution)

**Comment by jduan-highnote** [comment]
@int128 can you see if there's a bug? I'm seeing a lot of negative values for this metric collected by our jobs.

<img width="1928" alt="Metrics_Explorer___Datadog" src="https://github.com/int128/datadog-actions-metrics/assets/92047874/735df67e-6d32-404c-bf02-d13bd8bf7159">
