### ISSUE TITLE
Include attempt number into tags

### ISSUE THREAD

**Issue by RegFacu** [int128/datadog-actions-metrics#508]
I'd like to include the attempt number into the tags of the metrics payload to be able to filter them for some particular cases.

For example, this second attempt took 40 minutes while the first attempt took 1 hour and 20 minutes.
<img width="898" alt="image" src="https://user-images.githubusercontent.com/13556129/200011835-8de331ee-9de2-47f3-90bf-de0dbfcc82e8.png">
In average it represent 1 hour, but that is not completely true, the metric that I'm looking for is the 1 hour and 20 minutes to compare with other executions.

**Comment by RegFacu** [comment]
Any comment?

**Comment by int128** [comment]
Sounds good. Does the payload of workflow run has attempt count?

**Comment by int128** [comment]
I found `payload.workflow_run.run_attempt`. I will add a metric.
