### ISSUE TITLE
Pull request number

### ISSUE THREAD

**Issue by RegFacu** [int128/datadog-actions-metrics#563]
I'd like to include the pull request id into the metadata when we are running a workflow that is triggered by a pull request event.

**Comment by RegFacu** [comment]
I'm asking this to be able to get metrics about the amount of builds that are running for a particular PR.

**Comment by RegFacu** [comment]
Any chance of introduce this tag into the metrics?

**Comment by int128** [comment]
I added this feature as https://github.com/int128/datadog-actions-metrics/pull/597.

**Comment by RegFacu** [comment]
Thank you !
Will test it next week
