### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by chaimmintz** [int128/datadog-actions-metrics#581]
We need to connect to datadog through a proxy, is that supported?

**Comment by chaimmintz** [comment]
@int128 Any chance this can be supported?

**Comment by int128** [comment]
It seems datadog-api-client supports a proxy.
https://github.com/DataDog/datadog-api-client-typescript#configure-proxy

I will try the implementation.

**Comment by chaimmintz** [comment]
Thank you, very much appreciated!

**Comment by int128** [comment]
Could you try the latest release?

**Comment by chaimmintz** [comment]
Latest release works now with `https_proxy` env variable. Thank you!
