### ISSUE TITLE
Which GitHub Actions workflow permissions are required?

### ISSUE THREAD

**Issue by glenthomas** [int128/datadog-actions-metrics#614]
I see this error in my log when this action runs
```
Warning: Could not get the check suite: GraphqlError: Resource not accessible by integration
```
Which permission scopes do I need to add to the workflow for the GraphQL query to work?

**Comment by int128** [comment]
I noticed this issue when I created a new repository recently.
It seems the default permissions has been changed to read-only.
https://github.blog/changelog/2023-02-02-github-actions-updating-the-default-github_token-permissions-to-read-only/

I will update the doc.
