### ISSUE TITLE
Add support for custom tags

### ISSUE THREAD

**Issue by jnicoulaud-ledger** [int128/datadog-actions-metrics#821]
It would be nice to support adding custom tags, especially to set [Unified Service Tagging](https://docs.datadoghq.com/getting_started/tagging/unified_service_tagging) ones: `env`, `service`, `version`, `team`, etc

**Comment by int128** [comment]
Now this action supports `datadog-tags` option. Thank you for the feature request.

**Comment by jnicoulaud-ledger** [comment]
Awesome, thank you :+1:
